server:
  port: 1113
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1110/eureka/,http://localhost:1111/eureka/
spring:
  application:
    name: eureka-server

self:
  name: Jack
  age: 23