server:
  port: 1111
spring:
  application:
    name: eureka-register
eureka:
  instance:
    hostname: eureka-register2
  client:
    service-url:
      defaultZone: http://localhost:1110/eureka/,http://localhost:1111/eureka/
#  server:
#    enable-self-preservation: false #单机开发中关闭自我保护机制，以使注册中心能及时剔除失效的服务
